In [26]:
import orbslam3
import pandas as pd
import numpy as np
import cv2
from pathlib import Path

In [15]:
from orbslam_k2 import sync_video

In [3]:
PROJECT_DIR = Path("..") / ".."
DATA_DIR = PROJECT_DIR / "data"

In [4]:
GENERAL_OFFSET = pd.Timedelta(minutes=7)
LIGHT_START_LOGS = pd.Timedelta(minutes=31, seconds=42) + GENERAL_OFFSET
FLIGHT_START_VIDEO = pd.Timedelta(minutes=3, seconds=47) + GENERAL_OFFSET

PATH_TO_VOCABLUARY = PROJECT_DIR / "Vocabluary" / "ORBvoc.txt"
PATH_TO_CONFIG = PROJECT_DIR / "examples" / "k2" / "k2.yaml"
PATH_TO_VIDEO = DATA_DIR / "GX010294.MP4"
PATH_TO_LOGS = DATA_DIR / "log 19.12.22.csv"

In [17]:
slam = orbslam3.System(str(PATH_TO_VOCABLUARY), str(PATH_TO_CONFIG), orbslam3.Sensor.MONOCULAR)
# slam.set_use_viewer(True)
slam.initialize()


ORB-SLAM3 Copyright (C) 2017-2020 Carlos Campos, Richard Elvira, Juan J. Gómez, José M.M. Montiel and Juan D. Tardós, University of Zaragoza.
ORB-SLAM2 Copyright (C) 2014-2016 Raúl Mur-Artal, José M.M. Montiel and Juan D. Tardós, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: Monocular
Loading settings from ../../examples/k2/k2.yaml
	-Loaded camera 1
	-Loaded image info
	-Loaded ORB settings
	-Loaded viewer settings
	-Loaded Atlas settings
	-Loaded misc parameters
----------------------------------
SLAM settings: 
	-Camera 1 parameters (Pinhole): [ 1000 1000 1300 759 ]
	-Camera 1 distortion parameters: [  0 0 0 0 ]
	-Original image size: [ 5312 , 2988 ]
	-Current image size: [ 800 , 450 ]
	-Camera 1 parameters after resize: [  150.602 150.602 195.783 114.307 ]
	-Sequence FPS: 30
	-Features per image: 1000
	-ORB scale factor: 1.2
	-

Camera1.k3 optional parameter does not exist...
Viewer.imageViewScale optional parameter does not exist...
System.LoadAtlasFromFile optional parameter does not exist...
System.SaveAtlasToFile optional parameter does not exist...
System.thFarPoints optional parameter does not exist...


True

In [19]:
vid = cv2.VideoCapture(str(PATH_TO_VIDEO))
vid, fps = sync_video(vid, FLIGHT_START_VIDEO)

In [20]:
for i in range(20):
    _, frame = vid.read()
    # log = logs.iloc[i]
    slam.process_image_mono(frame, vid.get(cv2.CAP_PROP_POS_MSEC) / 1000, "")

First KF:0; Map init KF:0
New Map created with 242 points


In [23]:
trajectory = slam.get_trajectory_points()

In [29]:
trajectory

[(647.1798666666667,
  array([[ 9.9993485e-01, -2.9312654e-03,  1.1032001e-02, -3.3444643e-03],
         [ 2.6193843e-03,  9.9959946e-01,  2.8179612e-02, -2.1363589e-05],
         [-1.1110185e-02, -2.8148878e-02,  9.9954200e-01,  3.4605283e-02],
         [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  1.0000000e+00]],
        dtype=float32)),
 (647.2132333333334,
  array([[ 0.99990815, -0.00322625,  0.01316379, -0.00485147],
         [ 0.00279089,  0.9994528 ,  0.03295752, -0.00136322],
         [-0.01326292, -0.03291775,  0.99937004,  0.04060128],
         [ 0.        ,  0.        ,  0.        ,  1.        ]],
        dtype=float32)),
 (647.2466000000001,
  array([[ 0.99990386, -0.00308895,  0.01352085, -0.00378198],
         [ 0.002633  ,  0.9994315 ,  0.03361119,  0.00163567],
         [-0.01361699, -0.03357235,  0.99934345,  0.04190423],
         [ 0.        ,  0.        ,  0.        ,  1.        ]],
        dtype=float32)),
 (647.2799666666667,
  array([[ 9.9992085e-01, -3.38105